### PR TITLE
Add Microsoft.Bcl.AsyncInterfaces v9.0.0

### PR DESCRIPTION
**Pull request by Nytra**
This is needed to fix MonkeyLoader I think

### CODE REVIEW

**Comment by Banane9** [comment]
Not sure how much effect it will have, considering System.Linq.Async is still built against 6.0 🤔

**Comment by Banane9** [comment]
Just tested it with the EnumerableToolkit dlls replaced with the ones referencing the old Microsoft.Bcl.AsyncInterfaces and Resonite launches fine

**Comment by Nytra** [comment]
Hmm weird

**Comment by Nytra** [comment]
This is what I did in my custom build, I thought it was necessary

**Comment by Banane9** [comment]
It was 6.0 instead of 8.0 before too, so it would have been weird to suddenly break 🤔

**Pull request closed without merging**
